In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load dataset
df = pd.read_csv("../02_Data/Raw/ai4i2020.csv")

print("Original Dataset Shape:", df.shape)

# Remove unnecessary identifier columns
df.drop(columns=["UDI", "Product ID"], inplace=True)

# Encode categorical feature
encoder = LabelEncoder()
df["Type"] = encoder.fit_transform(df["Type"])

# Create temperature difference feature
df["Temperature Difference"] = (
    df["Process temperature [K]"] -
    df["Air temperature [K]"]
)

# Create tool wear categories
df["Tool Wear Level"] = pd.cut(
    df["Tool wear [min]"],
    bins=[0, 100, 200, df["Tool wear [min]"].max()],
    labels=["Low", "Medium", "High"],
    include_lowest=True
)

print("\nUpdated Dataset Shape:", df.shape)

print("\nNew Features")
display(
    df[
        [
            "Temperature Difference",
            "Tool Wear Level"
        ]
    ].head()
)

print("\nUpdated Dataset")
display(df.head())

Original Dataset Shape: (10000, 14)

Updated Dataset Shape: (10000, 14)

New Features

   Temperature Difference Tool Wear Level
0                    10.5             Low
1                    10.5             Low
2                    10.4             Low
3                    10.4             Low
4                    10.5             Low

Updated Dataset

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,Temperature Difference,Tool Wear Level
0,2,298.1,308.6,1551,42.8,0,0,0,0,0,0,0,10.5,Low
1,1,298.2,308.7,1408,46.3,3,0,0,0,0,0,0,10.5,Low
2,1,298.1,308.5,1498,49.4,5,0,0,0,0,0,0,10.4,Low
3,1,298.2,308.6,1433,39.5,7,0,0,0,0,0,0,10.4,Low
4,1,298.2,308.7,1408,40.0,9,0,0,0,0,0,0,10.5,Low

# Industrial Equipment Reliability Intelligence Platform

## Feature Engineering

This notebook creates meaningful features from the existing dataset to improve data analysis and support machine learning model development.